<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'
import {ElMessageBox} from 'element-plus'
import {useRoute,useRouter} from 'vue-router'
import {api,getData} from '../api'
import {useAuthStore} from '../stores/auth'

const auth=useAuthStore(),route=useRoute(),router=useRouter()
const group=ref(String(route.query.group||'protection')),tab=ref(''),rows=ref<any[]>([]),policies=ref<any[]>([]),archiveJobs=ref<any[]>([])
const error=ref(''),busy=ref(false),details=ref(''),previewOpen=ref(false),previewBusy=ref(false)
const previewPolicy=ref<any>(null),preview=ref<any>(null)
const groups=[{key:'protection',label:'数据保护',hint:'备份、快照与恢复证据'},{key:'ha',label:'高可用与归档',hint:'复制拓扑和归档作业'},{key:'governance',label:'组织与审计',hint:'用户、项目、环境和授权'}]
const allTabs=computed(()=>({
 protection:[{path:'/mysql/backups',label:'MySQL 备份'},{path:'/postgres/backups',label:'PostgreSQL 备份'},{path:'/doris/backups',label:'Doris 备份'},...(auth.user?.roles?.includes('SuperAdmin')?[{path:'/platform/backups',label:'平台快照'}]:[])],
 ha:[{path:'/mysql/replications',label:'MySQL 复制'},{path:'/mysql/archive/policies',label:'归档策略'},{path:'/mysql/archive/jobs',label:'归档作业'}],
 governance:[...(auth.user?.roles?.includes('SuperAdmin')?[{path:'/users',label:'用户'},{path:'/projects',label:'项目'},{path:'/environments',label:'环境'},{path:'/resource-scopes',label:'资源授权'}]:[]),...(auth.user?.roles?.some(r=>['SuperAdmin','Auditor'].includes(r))?[{path:'/audit',label:'操作审计'}]:[])],
} as Record<string,{path:string,label:string}[]>))
const tabs=computed(()=>allTabs.value[group.value]??[])
const canOperate=computed(()=>auth.user?.roles?.some(r=>['SuperAdmin','DBA','Operator'].includes(r)))
const canAdmin=computed(()=>auth.user?.roles?.some(r=>['SuperAdmin','DBA'].includes(r)))
const isPolicies=computed(()=>tab.value==='/mysql/archive/policies')
const isJobs=computed(()=>tab.value==='/mysql/archive/jobs')
const columns=computed(()=>[...new Set(rows.value.flatMap(r=>Object.keys(r)))].filter(k=>!['metadata_json','options_json','files','roles'].includes(k)).slice(0,10))
const fieldNames:Record<string,string>={id:'ID',name:'名称',status:'状态',source_instance_id:'源实例',source_database:'源库',source_table:'源表',destination_database:'目标库',destination_table:'目标表',policy_id:'策略 ID',task_id:'任务 ID',archived_rows:'归档行数',deleted_rows:'源表删除行数',created_at:'创建时间',finished_at:'结束时间'}
const statusNames:Record<string,string>={pending:'待执行',running:'执行中',success:'成功',failed:'失败',paused:'已暂停',pause_requested:'暂停中',stop_requested:'停止中',stopped:'已停止',interrupted:'待人工核查'}
const statusName=(value:string)=>statusNames[String(value).toLowerCase()]||value
const archiveNeedsCheck=(row:any)=>['failed','interrupted','stopped'].includes(row.status)
const archiveRetried=(row:any)=>rows.value.some(item=>Number(item.retry_of_job_id)===Number(row.id))
const archiveCount=(row:any,key:'archived_rows'|'deleted_rows')=>archiveNeedsCheck(row)&&!['ready_to_retry','verified_complete'].includes(row.verification_status)?'待核查':row[key]
const archiveResult=(row:any)=>archiveNeedsCheck(row)?`${archiveRetried(row)?'已创建重试作业；':row.verification_status==='ready_to_retry'?'核查通过，可重试；':row.verification_status==='verified_complete'?'核查通过，已全部归档；':row.verification_status==='manual_review'?'需要人工处理；':'待核查；'}${row.error_message||row.pause_reason||'作业未完成'}`:row.verification_status==='verified'&&row.baseline_json?'核查通过；':row.status==='success'?'命令完成；请核对目标表':row.error_message||row.pause_reason||'—'
const retryLink=(row:any)=>row.retry_of_job_id?`重试自 #${row.retry_of_job_id}`:archiveRetried(row)?`已生成重试 #${rows.value.find(item=>Number(item.retry_of_job_id)===Number(row.id))?.id}`:'—'
const archivePolicyUsed=(row:any)=>!row.delete_source&&archiveJobs.value.some(job=>Number(job.policy_id)===Number(row.id))
const policyName=(id:number)=>policies.value.find(p=>Number(p.id)===Number(id))?.name||`策略 #${id}`
const destination=(row:any)=>`${row.destination_database}.${row.destination_table}`
function tabFromQuery(){const key=String(route.query.tab||'');return tabs.value.find(x=>x.path.endsWith('/'+key))?.path||tabs.value[0]?.path||''}
async function selectGroup(key:string){group.value=key;tab.value=allTabs.value[key]?.[0]?.path||'';await router.replace({query:{group:key}});await load()}
async function selectTab(){await router.replace({query:{group:group.value,tab:tab.value.split('/').pop()}});await load()}
async function load(){if(!tab.value){rows.value=[];return}busy.value=true;error.value='';try{if(isJobs.value){const [items,related]=await Promise.all([getData<any[]>(tab.value),getData<any[]>('/mysql/archive/policies')]);rows.value=items??[];policies.value=related??[]}else if(isPolicies.value){const [items,jobs]=await Promise.all([getData<any[]>(tab.value),getData<any[]>('/mysql/archive/jobs')]);rows.value=items??[];archiveJobs.value=jobs??[]}else rows.value=(await getData<any[]>(tab.value))??[]}catch(e:any){error.value=e.response?.data?.message||e.message;rows.value=[]}finally{busy.value=false}}
async function previewArchive(row:any){previewPolicy.value=row;preview.value=null;previewOpen.value=true;previewBusy.value=true;error.value='';try{const response=await api.post(`/mysql/archive/policies/${row.id}/precheck`,{},{timeout:650000});preview.value=response.data.data}catch(e:any){error.value=e.response?.data?.message||e.message}finally{previewBusy.value=false}}
async function startArchive(){if(!previewPolicy.value||preview.value?.ok!==true)return;try{await ElMessageBox.confirm(`策略 ${previewPolicy.value.name} 将处理 ${previewPolicy.value.source_database}.${previewPolicy.value.source_table}，目标为 ${destination(previewPolicy.value)}。${previewPolicy.value.delete_source?'成功写入后会删除源记录。':''}请确认备份和筛选范围。`,'确认执行归档',{type:'warning'});previewBusy.value=true;const response=await api.post(`/mysql/archive/policies/${previewPolicy.value.id}/start`,{confirmed:true});previewOpen.value=false;await router.push({path:'/tasks',query:{id:response.data.data.id}})}catch(e:any){if(e!=='cancel'&&e!=='close')error.value=e.response?.data?.message||e.message}finally{previewBusy.value=false}}
async function action(row:any,verb:string){try{if(verb==='stop')await ElMessageBox.confirm(`停止归档作业 #${row.id}？已提交的批次不会回滚，结束后须核对源表与目标表。`,'确认停止',{type:'warning'});if(verb==='resume')await ElMessageBox.confirm(`恢复归档作业 #${row.id}？请先核对两张表的数据和上次任务结果。`,'确认恢复',{type:'warning'});if(verb==='reconcile')await ElMessageBox.confirm(`只读核查作业 #${row.id} 的源表、目标表主键集合和进程状态？核查期间请勿写入或修改两张表。`,'归档数据核查',{type:'warning'});if(verb==='retry')await ElMessageBox.confirm(`作业 #${row.id} 已通过只读核查。新作业将仅处理源表中仍符合原归档条件的记录；请确认两张表在核查后没有变化。`,'确认重试',{type:'warning'});busy.value=true;const response=await api.post(`${tab.value}/${row.id}/${verb}`,{confirmed:['stop','retry'].includes(verb)},{timeout:650000});const result=response.data.data;if(result?.task_type)await router.push({path:'/tasks',query:{id:result.id}});else{details.value=JSON.stringify(result,null,2);await load()}}catch(e:any){if(e!=='cancel'&&e!=='close')error.value=e.response?.data?.message||e.message}finally{busy.value=false}}
function showDetails(row:any){details.value=JSON.stringify(row,null,2)}
watch(()=>[route.query.group,route.query.tab],async()=>{const next=String(route.query.group||'protection');if(next!==group.value)group.value=next;const nextTab=tabFromQuery();if(nextTab!==tab.value){tab.value=nextTab;await load()}})
onMounted(async()=>{await auth.loadMe();tab.value=tabFromQuery();await load()})
</script>
<template>
 <div class="page-title"><div><h2>记录与治理</h2><p>按 DBA 工作场景查看保护结果、高可用状态和平台审计</p></div><el-button @click="load">刷新数据</el-button></div>
 <div class="record-groups"><div v-for="item in groups" :key="item.key" class="record-group" :class="{active:group===item.key}" @click="selectGroup(item.key)"><strong>{{item.label}}</strong><small>{{item.hint}}</small></div></div>
 <el-card shadow="never" class="surface-card">
  <el-tabs v-model="tab" @tab-change="selectTab"><el-tab-pane v-for="item in tabs" :key="item.path" :label="item.label" :name="item.path"/></el-tabs>
  <div v-if="isPolicies" class="filter-row"><span class="muted">创建策略后先预检查，再确认执行。</span><el-button v-if="canAdmin" type="primary" @click="router.push('/operations?category=ha&operation=创建归档策略')">创建归档策略</el-button></div>
  <el-alert v-if="error" :title="error" type="error" :closable="false"/>
  <el-alert v-if="isJobs&&rows.some(archiveNeedsCheck)" title="失败或中断后的计数可能不包含已提交批次。重试前请直接核对源表、目标表和归档条件。" type="warning" :closable="false" style="margin-bottom:12px"/>
  <el-table v-if="isPolicies" :data="rows" v-loading="busy" @row-dblclick="showDetails"><el-table-column prop="name" label="策略" min-width="150"/><el-table-column label="源表" min-width="190"><template #default="{row}">#{{row.source_instance_id}} {{row.source_database}}.{{row.source_table}}</template></el-table-column><el-table-column label="目标表" min-width="170"><template #default="{row}">{{destination(row)}}</template></el-table-column><el-table-column label="条件" min-width="230" show-overflow-tooltip><template #default="{row}"><code>{{row.where_template}}</code></template></el-table-column><el-table-column label="源表删除" width="105"><template #default="{row}">{{row.delete_source?'是':'否'}}</template></el-table-column><el-table-column v-if="canAdmin" label="操作" width="135" fixed="right"><template #default="{row}"><span v-if="archivePolicyUsed(row)" class="muted">已执行，需新建策略</span><el-button v-else link type="primary" @click="previewArchive(row)">预检查并执行</el-button></template></el-table-column></el-table>
  <el-table v-else-if="isJobs" :data="rows" v-loading="busy" @row-dblclick="showDetails"><el-table-column prop="id" label="作业 ID" width="90"/><el-table-column label="策略" min-width="170"><template #default="{row}">{{policyName(row.policy_id)}}</template></el-table-column><el-table-column label="状态" width="125"><template #default="{row}"><el-tag :type="row.status==='success'?'success':row.status==='failed'?'danger':'warning'">{{statusName(row.status)}}</el-tag></template></el-table-column><el-table-column label="写入行数" width="105"><template #default="{row}">{{archiveCount(row,'archived_rows')}}</template></el-table-column><el-table-column label="删除行数" width="105"><template #default="{row}">{{archiveCount(row,'deleted_rows')}}</template></el-table-column><el-table-column label="核查关系" width="145"><template #default="{row}"><span class="muted">{{retryLink(row)}}</span></template></el-table-column><el-table-column label="结果" min-width="230" show-overflow-tooltip><template #default="{row}">{{archiveResult(row)}}</template></el-table-column><el-table-column v-if="canOperate" label="操作" width="250" fixed="right"><template #default="{row}"><el-button v-if="row.task_id" link @click="router.push({path:'/tasks',query:{id:row.task_id}})">任务</el-button><el-button v-if="row.status==='running'" link @click="action(row,'pause')">暂停</el-button><el-button v-if="row.status==='paused'" link @click="action(row,'resume')">恢复</el-button><el-button v-if="canAdmin&&archiveNeedsCheck(row)&&row.baseline_json" link @click="action(row,'reconcile')">核查数据</el-button><el-button v-if="canAdmin&&row.verification_status==='ready_to_retry'&&!archiveRetried(row)" link type="primary" @click="action(row,'retry')">重试剩余</el-button><el-button v-if="canAdmin&&['running','pause_requested'].includes(row.status)" link type="danger" @click="action(row,'stop')">停止</el-button></template></el-table-column></el-table>
  <el-table v-else :data="rows" v-loading="busy" @row-dblclick="showDetails"><el-table-column v-for="key in columns" :key="key" :prop="key" :label="fieldNames[key]||key" min-width="150" show-overflow-tooltip/><el-table-column v-if="canOperate&&tab.endsWith('/replications')" label="操作" width="120"><template #default="{row}"><el-button size="small" @click="action(row,'refresh')">刷新状态</el-button></template></el-table-column></el-table>
  <el-empty v-if="!busy&&!rows.length" :description="group==='governance'?'当前没有可查看的治理记录':'暂无记录'"/>
 </el-card>
 <el-dialog v-model="previewOpen" :title="`归档预检查 · ${previewPolicy?.name||''}`" width="700px"><div v-loading="previewBusy"><p>源表：{{previewPolicy?.source_database}}.{{previewPolicy?.source_table}} → 目标表：{{previewPolicy&&destination(previewPolicy)}}</p><p>条件：<code>{{preview?.materialized_where||previewPolicy?.where_template}}</code></p><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-alert v-else-if="preview?.ok===false" :title="preview.reason||'预检查未通过'" type="error" :closable="false"/><el-alert v-else-if="preview?.ok" title="主键和 pt-archiver dry-run 已通过；仍需确认备份、目标空间和筛选范围。" type="success" :closable="false"/><pre v-if="preview?.dry_run_output" style="white-space:pre-wrap;max-height:250px;overflow:auto">{{preview.dry_run_output}}</pre><p v-if="previewPolicy?.delete_source" class="muted">执行后会删除已归档的源记录。任务失败时，已提交批次不会回滚。</p></div><template #footer><el-button @click="previewOpen=false">关闭</el-button><el-button v-if="canAdmin" type="primary" :disabled="preview?.ok!==true" :loading="previewBusy" @click="startArchive">确认并执行</el-button></template></el-dialog>
 <el-dialog :model-value="!!details" title="记录详情" width="70%" @close="details=''"><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{details}}</pre></el-dialog>
</template>
