<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {api,getData} from '../api'
const rows=ref<any[]>([]),instances=ref<any[]>([]),busy=ref(false),error=ref('')
const form=reactive({name:'',task_type:'mysql.backup',instance_id:0,interval_hours:24,output_dir:'/data/dbops-backup',repository:'',enabled:true})
const types=[{value:'mysql.backup',label:'MySQL 全库逻辑备份',engine:'mysql'},{value:'postgres.backup',label:'PostgreSQL 逻辑备份',engine:'postgres'},{value:'oracle.rman.backup',label:'Oracle RMAN Full',engine:'oracle'},{value:'doris.backup',label:'Doris Snapshot',engine:'doris'},{value:'platform.backup',label:'平台 SQLite 快照',engine:''}]
async function load(){try{[rows.value,instances.value]=await Promise.all([getData<any[]>('/backup-schedules'),getData<any[]>('/databases')])}catch(e:any){error.value=e.response?.data?.message||e.message}}
async function create(){busy.value=true;error.value='';try{const parameters=form.task_type==='platform.backup'?{}:{instance_id:form.instance_id,output_dir:form.output_dir,...(form.task_type==='mysql.backup'?{all_databases:true}:{}),...(form.task_type==='oracle.rman.backup'?{backup_type:'full'}:{}),...(form.task_type==='doris.backup'?{repository:form.repository}:{})};await api.post('/backup-schedules',{name:form.name,task_type:form.task_type,parameters,interval_seconds:Math.round(form.interval_hours*3600),enabled:form.enabled});await load()}catch(e:any){error.value=e.response?.data?.message||e.message}finally{busy.value=false}}
async function toggle(row:any){try{await api.put(`/backup-schedules/${row.id}`,{enabled:!row.enabled});await load()}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template><div class="page-title"><div><h2>定时备份</h2><p>按固定间隔生成持久化任务。错过的周期合并为一次执行，可随时停用。</p></div></div><el-alert v-if="error" :title="error" type="error"/>
<el-card shadow="never" style="margin-bottom:20px"><el-form label-position="top" @submit.prevent="create"><el-form-item label="计划名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="备份类型"><el-select v-model="form.task_type"><el-option v-for="t in types" :key="t.value" :label="t.label" :value="t.value"/></el-select></el-form-item><el-form-item v-if="form.task_type!=='platform.backup'" label="实例"><el-select v-model="form.instance_id"><el-option v-for="i in instances.filter(i=>i.db_type===types.find(t=>t.value===form.task_type)?.engine)" :key="i.id" :value="i.id" :label="`#${i.id} ${i.name}`"/></el-select></el-form-item><el-form-item label="执行间隔（小时）"><el-input-number v-model="form.interval_hours" :min="1" :max="8784" :precision="0"/></el-form-item><el-form-item v-if="form.task_type==='doris.backup'" label="Doris Repository"><el-input v-model="form.repository"/></el-form-item><el-form-item v-else-if="form.task_type!=='platform.backup'" label="备份目录"><el-input v-model="form.output_dir"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled"/></el-form-item><el-button type="primary" native-type="submit" :loading="busy">保存计划</el-button></el-form></el-card>
<el-card shadow="never"><el-table :data="rows"><el-table-column prop="name" label="计划"/><el-table-column prop="task_type" label="类型"/><el-table-column prop="next_run" label="下次执行 UTC" min-width="190"/><el-table-column prop="last_task_id" label="最近任务"/><el-table-column prop="last_error" label="最近错误" show-overflow-tooltip/><el-table-column label="状态"><template #default="{row}"><el-button @click="toggle(row)">{{row.enabled?'停用':'启用'}}</el-button></template></el-table-column></el-table></el-card></template>
