export interface Field { key: string; label: string; type?: 'number'|'password'|'boolean'|'select'|'list'; value?: any; choices?: string[]; source?: 'agents'|'packages'|'databases'; engine?: string; required?: boolean }
export interface Operation { name: string; path: string; roles: string[]; risk?: string; fields: Field[] }
const dba = ['SuperAdmin','DBA'], ops = [...dba,'Operator']
const agent: Field = {key:'agent_id',label:'目标 Agent',type:'select',source:'agents',required:true}
const instance = (engine: string): Field => ({key:'instance_id',label:'数据库实例',type:'select',source:'databases',engine,required:true})
const name: Field = {key:'name',label:'名称',required:true}
const output: Field = {key:'output_dir',label:'Agent 上的备份目录',value:'/data/dbops-backup',required:true}
const credentials: Field[] = [{key:'username',label:'数据库用户名',required:true},{key:'password',label:'数据库密码',type:'password',required:true}]
export const operations: Operation[] = [
 {name:'MySQL 安装预检查',path:'/mysql/precheck',roles:dba,fields:[agent,{key:'port',label:'端口',type:'number',value:3306},{key:'install_root',label:'安装根目录',value:'/opt/dbops'},{key:'data_dir',label:'自定义数据目录（可选）'}]},
 {name:'安装 MySQL',path:'/mysql/install',roles:dba,risk:'将在目标主机创建目录、初始化 MySQL 并启动 systemd 服务。请先完成安装预检查。',fields:[agent,name,{key:'package_id',label:'MySQL 软件包',type:'select',source:'packages',required:true},{key:'port',label:'端口',type:'number',value:3306},{key:'install_root',label:'安装根目录',value:'/opt/dbops'},{key:'service_name',label:'自定义服务名称（可选）'},{key:'base_dir',label:'自定义程序目录（可选）'},{key:'data_dir',label:'自定义数据目录（可选）'},{key:'log_dir',label:'自定义日志目录（可选）'},{key:'binlog_dir',label:'自定义 Binlog 目录（可选）'},{key:'run_dir',label:'自定义运行目录（可选）'},{key:'config_path',label:'自定义配置文件路径（可选）'},{key:'innodb_buffer_pool_bytes',label:'Buffer Pool（字节）',type:'number',value:1073741824},{key:'max_connections',label:'最大连接数',type:'number',value:200},{key:'manage_os_user',label:'创建 MySQL 系统用户',type:'boolean',value:true}]},
 {name:'建立 MySQL GTID 复制',path:'/mysql/replications',roles:dba,risk:'将修改副本复制配置。请使用已初始化且符合预检查要求的副本。',fields:[{...instance('mysql'),key:'primary_instance_id',label:'主库'},{...instance('mysql'),key:'replica_instance_id',label:'副本'},{key:'baseline_ready',label:'已核实副本数据基线与主库一致',type:'boolean',value:false}]},
 {name:'MySQL 备份',path:'/mysql/instances/:id/backups',roles:ops,fields:[instance('mysql'),{key:'engine',label:'备份引擎',type:'select',choices:['mysqldump','xtrabackup'],value:'mysqldump'},{key:'tool_path',label:'XtraBackup 路径（物理备份可选）'}, {key:'all_databases',label:'备份所有数据库',type:'boolean',value:true},{key:'databases',label:'指定数据库（逻辑备份可选）',type:'list'},output]},
 {name:'MySQL 新主机恢复',path:'/mysql/restores/new-host',roles:dba,fields:[{key:'backup_id',label:'成功备份 ID',type:'number',required:true},agent,name,{key:'package_id',label:'同版本 MySQL 软件包',type:'select',source:'packages',required:true},{key:'port',label:'新实例端口',type:'number',value:3306},{key:'install_root',label:'安装根目录',value:'/opt/dbops'},{key:'service_name',label:'自定义服务名称（可选）'},{key:'tool_path',label:'XtraBackup 路径（物理备份可选）'},{key:'manage_os_user',label:'创建 MySQL 系统用户',type:'boolean',value:true}]},
 {name:'MySQL 备份恢复',path:'/mysql/restores',roles:dba,risk:'仅允许恢复到同一 Agent 上另一台同版本、无业务库的实例。物理备份仅 prepare 并恢复到独立暂存目录，需人工核查后停库切换；逻辑恢复失败须人工核查目标。',fields:[{key:'backup_id',label:'成功备份 ID',type:'number',required:true},{...instance('mysql'),key:'target_instance_id',label:'空白目标实例'},{key:'tool_path',label:'XtraBackup 路径（物理恢复可选）'}]},
 ...['start','stop','restart'].map((action): Operation => ({name:`MySQL ${ {start:'启动',stop:'停止',restart:'重启'}[action] }`,path:`/mysql/instances/:id/${action}`,roles:ops,risk:action==='start'?undefined:'此操作会中断该实例的数据库连接。',fields:[instance('mysql')]})),
 {name:'纳管 Oracle',path:'/oracle/instances',roles:dba,fields:[agent,name,{key:'port',label:'监听端口',type:'number',value:1521},{key:'oracle_home',label:'ORACLE_HOME',required:true},{key:'oracle_sid',label:'ORACLE_SID',required:true},...credentials]},
 {name:'Oracle 新增 Datafile',path:'/oracle/instances/:id/datafiles',roles:dba,risk:'将创建数据文件并修改表空间。',fields:[instance('oracle'),{key:'tablespace',label:'表空间',required:true},{key:'file_path',label:'数据文件完整路径',required:true},{key:'size_mb',label:'初始大小 MB',type:'number',value:1024},{key:'autoextend',label:'自动扩展',type:'boolean',value:false},{key:'next_mb',label:'扩展步长 MB',type:'number',value:128},{key:'max_mb',label:'上限 MB',type:'number',value:32768}]},
 {name:'Oracle 扩大 Datafile',path:'/oracle/instances/:id/datafiles/resize',roles:dba,risk:'仅支持扩大文件，请确认剩余磁盘容量。',fields:[instance('oracle'),{key:'file_path',label:'数据文件路径',required:true},{key:'target_size_mb',label:'目标大小 MB',type:'number',value:2048}]},
 {name:'Oracle RMAN 备份',path:'/oracle/instances/:id/backups/rman',roles:ops,fields:[instance('oracle'),{key:'backup_type',label:'备份类型',type:'select',choices:['full','level0','level1','archivelog'],value:'full'},output]},
 {name:'纳管 PostgreSQL',path:'/postgres/instances',roles:dba,fields:[agent,name,{key:'bin_dir',label:'PostgreSQL bin 目录',required:true},{key:'host',label:'数据库地址',value:'127.0.0.1',required:true},{key:'port',label:'端口',type:'number',value:5432},{key:'database',label:'数据库名',value:'postgres',required:true},...credentials]},
 {name:'PostgreSQL 逻辑备份',path:'/postgres/instances/:id/backups',roles:ops,fields:[instance('postgres'),output]},
 {name:'纳管 Doris',path:'/doris/instances',roles:dba,fields:[agent,name,{key:'mysql_client',label:'mysql 客户端完整路径',required:true},{key:'host',label:'FE 地址',required:true},{key:'query_port',label:'查询端口',type:'number',value:9030},{key:'database',label:'数据库名',required:true},...credentials]},
 {name:'Doris Snapshot 备份',path:'/doris/instances/:id/backups',roles:ops,fields:[instance('doris'),{key:'repository',label:'Repository',required:true},{key:'label',label:'Snapshot 标签（可自动生成）'},{key:'tables',label:'表名（逗号分隔）',type:'list'}]},
 {name:'创建归档策略',path:'/mysql/archive/policies',roles:dba,fields:[name,{...instance('mysql'),key:'source_instance_id',label:'源实例'},{key:'source_database',label:'源数据库',required:true},{key:'source_table',label:'源表',required:true},{key:'where_template',label:'筛选条件（支持 {{cutoff}}）',required:true},{key:'retention_days',label:'保留天数',type:'number',value:90},{key:'destination_type',label:'目标类型',type:'select',choices:['table'],value:'table'},{...instance('mysql'),key:'destination_instance_id',label:'目标实例'},{key:'destination_database',label:'目标数据库',required:true},{key:'destination_table',label:'目标表',required:true},{key:'batch_size',label:'批大小',type:'number',value:1000},{key:'sleep_ms',label:'批次间隔 ms',type:'number',value:100},{key:'max_replication_lag',label:'复制延迟上限 秒',type:'number',value:10},{key:'delete_source',label:'删除已归档源记录',type:'boolean',value:false},{key:'enabled',label:'启用',type:'boolean',value:true}]},
 {name:'创建平台快照',path:'/platform/backups',roles:['SuperAdmin'],fields:[]},
 {name:'创建项目',path:'/projects',roles:['SuperAdmin'],fields:[name]},
 {name:'创建环境',path:'/environments',roles:['SuperAdmin'],fields:[name,{key:'code',label:'环境代号（如 production）',required:true}]},
 {name:'设置主机资源范围',path:'/resource-scopes',roles:['SuperAdmin'],fields:[{key:'host_id',label:'主机 ID',type:'number',required:true},{key:'project_id',label:'项目 ID',type:'number',required:true},{key:'environment_id',label:'环境 ID',type:'number',required:true}]},
 {name:'用户资源授权',path:'/resource-scopes',roles:['SuperAdmin'],fields:[{key:'user_id',label:'用户 ID',type:'number',required:true},{key:'project_id',label:'项目 ID',type:'number',required:true},{key:'environment_id',label:'环境 ID',type:'number',required:true},{key:'granted',label:'授予访问（关闭则撤销）',type:'boolean',value:true}]},
 {name:'创建用户',path:'/users',roles:['SuperAdmin'],fields:[{key:'username',label:'用户名',required:true},{key:'display_name',label:'显示名称'},{key:'password',label:'初始密码',type:'password',required:true},{key:'role',label:'角色',type:'select',choices:['DBA','Operator','Viewer','Auditor'],value:'Viewer'}]},
]
